sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - abbyxu@amazon.com
env:
  matrix:
    - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
#  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
    - secure: exCVOaPimOd/phibSTt3XusM0atNsAlUqQ2BSVWJlh6diPP5zNLY6GvytU1oUAZm0TmCNLcryU9NQDPvfqsLHxWf1Yretgy+n/qlsMgBZLVzyCpTllCYpo7ExKSjIAUFdHnGVvNMT53D/Gs1kLY5BYrFFhzYas5LyJ1r0r+pPvGDktrarQD9QWxrLzw+bW/32jS3UxQr6oGMi5k3wGAtpgHGwJxe/Ly1vKvC1M+yAPGNUTnMxymiRyaN0KqHWUlDC/lPZjQLlXsORdU0HE8/YT7bJrd0evTE32ld4n5sgH5utcfmttLyWmtSd8yt7pk2KBJtgj9lYBzubn2p8cpUMnYankKbvUr+tYSsqtX3jPrfBU7bKWCkbaBszCPPXWkM7NIrlqGjXCO9MCKvafK0D0Z3uqsEryfDjjgUFTRcB6+LWqSoN02I+MKI7K86fTbnEehMD9ipdFnz/LANG4tegdqj80X4jP3krAtD06w14cEvTVDGR7Y5vAIKJqGXxinHYeUfjrkA/cUnqerw9vzZrntZfwzI5iCUbU1m1eR2EVyBXOyIFCF5BvjPgR9pLOQAgRyrsC5DgjgHFxCBdPvshB2wfIDLT3LAj+9jCsftMgwKdUxvU+/HFEEUmwUh/JoBslnGAPavJX0N5AMyw38gv86AGCyV+Y175PWLGDo1BQA=
    - secure: EZbhWIt+zBvFSd0S3G2NZ+WQXsRaX2whXNdZjBxElU2xs41CdlZlwIAuZEGPYb4geMCpG6zEEIHzU3sAKmQB2que9ocP8I2R1P195BLXlqhfJXfc9UO8eQsGhq9jABj0WaGdV2gJY0cvr4t/zP9bWrDajx3K02uyJ7EVPjpaW5wYrpaVh7zfUqcNoBafrKx/6ZY9BX18+HFmRPT/fMVpFKBF6PX8V7bE5AhbOyFx+9ivHXOZWb6xVBtDzyYl2yS8C6wL3F1PQQXvY+svXeGtNDI1r5edPWPdiTdAjzuHmwhvw2QaHbhq4kqQd4ql8YN/FvZvuOch0vLLfzZ5whG3j+3vPzdGYWkwwhDgh0drp/UsphU3XuyLeLDixPJz98g0GvOWD1TCNldmkKVbcQ/mUA72CMriwfvATKJIfkeiGJ7DrFdfsL97luU3oy5Qg0gNXXlCZWUYz1qp5mybCxK+ZMvOqc/OG28lxgXR8P5zRqb9sU2PD6VtDd9Srlm3D3zUtDVf1qjsa2zfpTpm0aHo9RmjEQReFO91xCI93inTd0bhVlZsckRkbuzWpls+lbklm6G4Vbhto4W1kHhnhvcVV4tQy7XFJ/NMogq8jxpgnqk3niX/VCvCpmJpTqzLpH+q8RZox/S8ZfU7gmleQHBAHFxLuT7a+cKd9719ibICz4I=
    - SA_NAME=hello-world
    - SA_PACKAGE_NAME=hello_world_robot
    - NO_TEST=true
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
    - CC_REPO_NAME=t-1
before_install:
  - pip install --user awscli
#  - openssl aes-256-cbc -K $encrypted_e9b424f4a194_key -iv $encrypted_e9b424f4a194_iv
#    -in github_deploy.pem.enc -out github_deploy.pem -d
install:
  - git clone https://github.com/xabxx/travis-scripts-1.git .ros_ci
#script:
#  - . .ros_ci/add_tag.sh
#  - .ros_ci/ce_build.sh
before_deploy:
- .ros_ci/before_deploy.sh
deploy:
#  - provider: s3
#    access_key_id: "$AWS_ACCESS_KEY_ID"
#    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
#    bucket: "$S3_BUCKET_NAME"
#    local_dir: shared
#    skip_cleanup: true
#    wait-until-deployed: true
#    on:
#      branch: master
#    upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
  - provider: script
    script: bash .ros_ci/codepipeline_deploy.sh
    on:
      branch: master
#after_deploy:
#  - .ros_ci/post_deploy.sh
