sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - abbyxu@amazon.com
env:
  matrix:
    - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
#  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
    - secure: pZAPv8SfX2Bgl6+yRrabAJqoCcGtgs1+gjtiuIR19LMtXn+tI3tRTrl8ax6dKWpGD8ESLN1ui0ITr8ukdkuJYf8uj/joTELfVPLfpJhF6wIfvBqVFn8SVXfmUXtcO/wEzBIDz7I87giLEzkky2sB57HcUfjdC/TKiCQN6qfEXiVTbXXW5EoWkjsnwrMC1yMUR0YPDXOjkxFkEnrrChnXQjpB5l/BM/IH//jacgqSJRonXGMPncU4SKCwSEpdgvh4MYb6yTUoDlbvVzwG7tNEbFVOQjwPIN/vm2PuULXJzHPPZyTKxuIuqvKqOtinVO06tfBCM3Y1mvY5JupBJm3o0tluSu6I9FH8oXSIz5Fox8wGaJpi8t+2orekfNCdaByda0AMLhheMLTXou9zG68RCei9KtwVCr2cqNFIuLp1mJ4gWeEigeZ0pbZC+VZHvfbWCWnPdRN59Msqy0e1llxxpt9nDfgA37KCH6Hn35rmCQCelSxeA/OXrvSbl5Xr27aL/PxipxH5peubgfAsdiqHttSl8zIDDRsIal2/4gQwTRkkQsKFjq/yE6OzJoof2FRCLwbY65t/Qqj7V6WAs/XdSvR8GhMAkE20763JVXCLSPHkSb8jztfCdiAY1flAon0uGVoLGcHlwaHUR98kgArO4IFdrp+wyX8oAmYTLSEcTC0=
    - secure: rLzekKLUdCCVL1M8cUTs65a9jW2XP2L0kCVBj33gsl/2f6w3tS1hPJ+CKQXsIhKWiejJ4hn7SpL6MpH0rJITenquYZlZ9+bhukQPzp/ILOhk11tADh2OooNYjLIftmjk86gPTnE2iVkQ1wv4cpiXmRI/XaPmVypb00UYPoJ/IdRrwzTZl39woU2iCSk9PKWeqBOCVIFhDQAb886wmvKxxDOoZdIkYGOy92D1QXtCwEG+mtVN9s0beITyeANGYifesPV2JVe+PKis1H98sqMICo/YVZPkoV03hOKUcoROL9kBewZG8WliF98Cuk4pBmnQ+SiEIC/6Ee7PrBgFuXpmymiCFqG4X/CAQ78ENMFZmGk1JRN1ZbqyUWJ+a/X02YE9a+L1ItRuKocJ2ezs9sjxipUKXiJte1FVj0t56lm3fBRazjUCfIuls8UVbNWAArcrvE+APFOgYihIJrERSaE2OqANIb4ILP9NoLsDVa73Yfbz4yj4yXyJG+YvyDlACKsgmgQwIMPOtoOjpd5QOAQcjVNbIfIlwRH+HSE2gB8a+NE4PonosA6l2olwTg3x4IImkfM4XyLXvmUNCjp2KQj9hmbJqof/bUnKhfAgkD72+QREKsloUY2+NBheJPKqow0KllQVxkIeKzNPy3JZr6HXKth4IawlDhkk7MaeTwom+KY=
    - SA_NAME=hello-world
    - SA_PACKAGE_NAME=hello_world_robot
    - NO_TEST=true
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
    - CC_REPO_NAME=t-1
before_install:
  - pip install --user awscli
#  - openssl aes-256-cbc -K $encrypted_e9b424f4a194_key -iv $encrypted_e9b424f4a194_iv
#    -in github_deploy.pem.enc -out github_deploy.pem -d
install:
  - git clone https://github.com/xabxx/travis-scripts-1.git .ros_ci
#script:
#  - . .ros_ci/add_tag.sh
#  - .ros_ci/ce_build.sh
before_deploy:
- .ros_ci/before_deploy.sh
deploy:
#  - provider: s3
#    access_key_id: "$AWS_ACCESS_KEY_ID"
#    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
#    bucket: "$S3_BUCKET_NAME"
#    local_dir: shared
#    skip_cleanup: true
#    wait-until-deployed: true
#    on:
#      branch: master
#    upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
  - provider: script
    script: bash .ros_ci/codepipeline_deploy.sh
    on:
      branch: master
#after_deploy:
#  - .ros_ci/post_deploy.sh
