sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - abbyxu@amazon.com
env:
  matrix:
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
  global:
  - SA_NAME=hello-world
  - SA_PACKAGE_NAME=hello_world_robot
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - CC_REPO_NAME=t-1
  - secure: zjOFGQMQuxE7uiTqBmFkyulo4snSTQncr3lXw0JTUEbRpG0adFxA+52T9xjH2gT9mC+U/vPRBUx7TbnlePEzTTlRhisWFaH2WcIM1CvL815TTZcdEmYWn6IbVdzskFPU/DM1P/cNJ3MPOs5W2sN0wH5VaqYzWD/eEjCeTd4B92vIBYz/c4muh/2dt43WpXsG7Van5e8zRydvww4NbKDm/4HAM/+CqggRMtiItXlmMq9wSs3eFQJTgf7bDTAjK0jjIuLzFTF5d7NtHJdIVVD8im1A9uaPEo3tZF8e/I/5xYJ0w4q4ovrmHkX+m4M5Hs+f8sk+9eH69GQmagfZRBvcFTlpuyRFvyRTuG6x7uYwoiZTY7XGSCCJDbez3SMoz69aCGB/H6oR2eZvby8d9Gdv9zjTV15W0qQa9zHPIU8MDYoVh5TvTOjRe40Gwu+k2LLA1MLPmiBRz3iTHPJA+VVmGhicaQplMtK72VWubx3KUy31wuclueAu824rzQdiopACnT4aNkGYd4LRYTxNBl7NscgkFYl+YqSLwUKssCgIliIVUEwUvW2f1H3BCAWGX5Q++ZzRcZ0KX7aRcUQYqO0hSfDT45yfVg0a75jG5ny5dYMolds6y0/oakDGwccZubxuJ/rTIX5POmu62HKG2H118o690Pee6fHb6vyyfpJC2Ds=
  - secure: h+9wHfhdF8NIiJl2na/bU7Fu70RJ4Vn6Z6oK6mV36s6aLF7TXicQLcsNqr5s3n28IuSgeMA+BiLvI8Enu2s8Sg0St8HT8/NLzV2f88X161L0x6DgzIcDiyYx4ANyeTQzCaSk6GaV9Nrb8ujKaxkGlcARr0wAeBqJjjmbGDkx0KrKFNZgk9wUj4J1x0ziscfC3PuU4k3vJmNGx022LpdC7qSRBnGdU2YaWXCjYGINBpw4rbfLMMLlGY+5Iexben8mANqcXg+dPNfkSjgVPuOwsWKTQe8UD0dpSPyB89B4iHHYNQws8ybDzE2y1PLdhhGk6/+2EWtRKHKE64HokgcDxGsfYwn8LNuveaGgc9v5EaPTDVtZEWc9zkWut+O7IZ3AixX05IHUwHj+ngHdXiWpTsYsVub+yty8lySrgScHD0dijodDeXKrPcqe1ffcGOoSiMBUc00K+KOhTqHNBdXuWV/QQRp55UX6U69fBH0qCVzDy2byPTDO2YOLCupfSc3z+67u4ziLZRUxBA9/O6NuRVGb7b4qchR4YGLMT/ZOZmY9M8JrXW/rkGv0550uFJqzkzNUvYyjJhLM/DlB0HG06O4Lov+d3D755BqsrNlkSomKt2upe6jcwwrkBymN8FVKccKxsNALRryu0cXReU80sQoMm3lvtYcbNTyDEC0by3k=
before_install:
- pip install --user awscli
install:
- git clone https://github.com/xabxx/travis-scripts-1.git .ros_ci
before_deploy:
- sudo chmod +x .ros_ci/*
- ".ros_ci/cc.sh"
- ".ros_ci/before_deploy.sh"
deploy:
- provider: script
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  script: . .ros_ci/codepipeline_deploy.sh
  on:
    branch: master
